<a href="https://colab.research.google.com/github/SophrosyneEunoia/Notes/blob/main/0%20-%20Introduction%20to%20Python/Introduction%20to%20Numerical%20Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### 1 - Understanding NumPy Arrays

In [2]:
arr = np.array([1,2,3,4,5,6])

print(arr)

[1 2 3 4 5 6]


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
arr_dua = np.array([[1,2,3],[4,5,6]])

print(arr_dua)

[[1 2 3]
 [4 5 6]]


In [5]:
arr_tiga = np.array([[*range(1,4)],[*range(4,7)],[*range(7,10)]])

print(arr_tiga)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print("Shape")
print(arr.shape)
print(arr_dua.shape)
print(arr_tiga.shape)

Shape
(6,)
(2, 3)
(3, 3)


In [7]:
print("Dimension")
print(arr.ndim)
print(arr_dua.ndim)
print(arr_tiga.ndim)

Dimension
1
2
2


In [8]:
print("Size")
print(arr.size)
print(arr_dua.size)
print(arr_tiga.size)

Size
6
6
9


In [9]:
print("len")
print(len(arr))
print(len(arr_dua))
print(len(arr_tiga))

len
6
2
3


In [10]:
zero = np.zeros((2,2))

print(zero)

[[0. 0.]
 [0. 0.]]


In [11]:
rand = np.random.random((3,3))

print(rand)

[[0.92595812 0.76547574 0.98603636]
 [0.45036851 0.60872386 0.06903094]
 [0.98324693 0.97984385 0.75769572]]


In [12]:
arange = np.arange(1,11)

print(arange)

[ 1  2  3  4  5  6  7  8  9 10]


### 2 - Selecting and Updating Data

### 3 - Array Mathematics!

### 4 - Array Transformations

NumPy vs List
1. List can have multiple data type, meanwhile numpy is only for single data type